# Generated by Django 4.1.5 on 2023-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, default='Yeni Ürün', max_length=240, verbose_name='Ürün İsmi')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('photo', models.CharField(default='https://t4.ftcdn.net/jpg/04/70/29/97/360_F_470299797_UD0eoVMMSUbHCcNJCdv2t8B2g1GVqYgs.jpg', max_length=800, verbose_name='Ürün Resim Linki')),
                ('activity', models.BooleanField(verbose_name='Aktiflik Durumu')),
            ],
        ),
    ]
