# Generated by Django 4.1.5 on 2023-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, default='Yeni Ürün', max_length=240, verbose_name='Şirket İsmi')),
                ('photo', models.CharField(default='https://t4.ftcdn.net/jpg/04/70/29/97/360_F_470299797_UD0eoVMMSUbHCcNJCdv2t8B2g1GVqYgs.jpg', max_length=800, verbose_name='Şirket Resim Linki')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, default="<i class='bi bi-chat-square-quote-fill'></i>", max_length=500, verbose_name='Bootstrap Icon Kodu')),
                ('link', models.CharField(blank=None, default='https://www.instagram.com/h.denizkaraman/', max_length=800, verbose_name='Sosyal Medya Linki')),
                ('activity', models.BooleanField(verbose_name='Aktiflik Durumu')),
            ],
        ),
    ]
