# Generated by Django 4.1.5 on 2023-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_companyinfo_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=200, null=True, unique=True),
        ),
    ]
