# Generated by Django 4.1.5 on 2023-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=None, default=30, null=None, verbose_name='Ürün Fiyatı'),
            preserve_default=False,
        ),
    ]
